[x_motor]
step_pin_ID = 21
dir_pin_ID = 27
comm_port = "/dev/ttyUSB1"
high_sensitivity = false

[x_motor.microstepping]
resolution = "full"
full_steps_per_rev = 200

[x_motor.current]
run_current_pct = 71.0
hold_current_pct = 10.0

[y_motor]
step_pin_ID = 19
dir_pin_ID = 20
comm_port = "/dev/ttyUSB0"
high_sensitivity = false

[y_motor.microstepping]
resolution = "full"
full_steps_per_rev = 200

[y_motor.current]
run_current_pct = 71.0
hold_current_pct = 10.0
